BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "TodoList" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Description"	TEXT,
	"IsDone"	INTEGER NOT NULL,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
INSERT INTO "TodoList" VALUES (2,'Gå med hunden','',0);
INSERT INTO "TodoList" VALUES (3,'Vask tøj','',0);
COMMIT;
